name: Is Organization Member Example

on:
  issues:
    types: [opened, labeled]

jobs:
  is-member:
    name: Is org member?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Check if organization member
        id: is_organization_member
        uses: zuchka/community-actions@v0.0.6
        with:
          username: ${{ github.event.issue.user.login }}
          teammates: 20k-ultra|char8|coffee-cup|dbanys|FarazPatankar|gschier|half0wl|JakeCooper|jitachi|melissa-hale|ndneighbor|ohrgaard|pierre-borckmans|railway-bot|tacLog|trif0lium|zuchka
      - name: Create Comment
        if: |
          !${{ steps.is_organization_member.outputs.result }}
        run: echo User Does Not Belong to testorg
      - name: Create Comment 2
        if: |
          ${{ steps.is_organization_member.outputs.result }}
        run: echo User Belongs to testorg
