name: Is Organization Member Example

on:
  issues:
    types: [opened, labeled]

jobs:
  is-member:
    name: Is org member?
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        if: github.event.action == 'opened'
        uses: zuchka/is-organization-member@0.0.1
        with:
          organization: railwayapp
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Comment for external
        if: |
          ${{ steps.is_organization_member.outputs.result == 'false' }}
        run: echo User Does Not Belong to testorg. result = ${{ steps.is_organization_member.outputs.result}}
