name: Is Org Member

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

jobs:
  is-member:
    name: Is org member?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Check if organization member
        id: is_organization_member
        uses: zuchka/community-actions@v0.0.19
        env:   
          GITHUB_ISSUE_URL: ${{ toJson(github.event.issue) }}
          GITHUB_ISSUE_TITLE: ${{ toJson(github.event.issue.title) }}
          GITHUB_ISSUE_BODY: ${{ toJson(github.event.issue.body) }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}   
        with:
          username: ${{ github.event.issue.user.login }}
          teammates: 20k-ultra|char8|coffee-cup|dbanys|FarazPatankar|gschier|half0wl|JakeCooper|jitachi|melissa-hale|ndneighbor|ohrgaard|pierre-borckmans|railway-bot|tacLog|trif0lium|zuchka
